"""Run each search method over a range of ell, and save every Legendre pair
found into a Markdown file -- one table per method.

Each table has columns: ell, the pair (A / B as +/- strings), the search time,
and the algorithm parameters used (when they make sense for that method).

Methods covered
---------------
* exhaustive : incremental early-stop bucket scan (find_one_legendre_pair).
* greedy / sideways / anneal / threshold / basinhop : local search on the PAF
  objective (local_search.search).
* continuous : continuous gradient descent (continuous_descent) -- included for
  completeness; it finds no pairs, so it is reported as a note, not a table.

Usage
-----
    python3 collect_pairs.py                      # ell = 5..21, seed 0
    python3 collect_pairs.py --min 5 --max 25 --seed 3
    python3 collect_pairs.py --restarts 300 --steps 20000 --out found_pairs.md
"""

from __future__ import annotations

import argparse
import time

import numpy as np

from legendre import find_one_legendre_pair, is_legendre_pair
from local_search import search
from continuous_descent import one_run as continuous_run

LOCAL_STRATEGIES = ("greedy", "sideways", "anneal", "threshold", "basinhop")


def _fmt(seq) -> str:
    return "".join("+" if x == 1 else "-" for x in seq)


def collect(lengths, restarts, steps, t0, t_end, seed):
    """Return {method: [row, ...]} plus a continuous-descent summary dict."""
    results = {"exhaustive": []}
    for m in LOCAL_STRATEGIES:
        results[m] = []

    for ell in lengths:
        # exhaustive
        tic = time.perf_counter()
        pair = find_one_legendre_pair(ell)
        dt = time.perf_counter() - tic
        if pair is not None:
            a, b = pair
            results["exhaustive"].append({
                "ell": ell, "A": _fmt(a), "B": _fmt(b), "time": dt,
                "params": "PAF-bucket, incremental early-stop, sum=1",
            })

        # local-search strategies
        for m in LOCAL_STRATEGIES:
            res = search(ell, strategy=m, restarts=restarts, steps=steps,
                         t0=t0, t_end=t_end, seed=seed)
            if res["solved"]:
                if m == "anneal":
                    params = (f"restarts_used={res['restarts_used']}, steps={steps}, "
                              f"t0={t0}, t_end={t_end}, seed={seed}")
                else:
                    params = (f"restarts_used={res['restarts_used']}, steps={steps}, "
                              f"seed={seed}")
                results[m].append({
                    "ell": ell, "A": _fmt(res["A"]), "B": _fmt(res["B"]),
                    "time": res["seconds"], "params": params,
                })

    # continuous descent: a single stable (normalized) pass per length
    rng = np.random.default_rng(seed)
    cont_solved = 0
    cont_best = []
    for ell in lengths:
        r = continuous_run(ell, steps=3000, eta=1.0 / (2 * ell), normalize=True,
                           project="none", rng=rng)
        cont_best.append(r["best_round"])
        if r["found"] is not None:
            cont_solved += 1
    continuous = {"solved": cont_solved, "total": len(lengths),
                  "best_round": cont_best}
    return results, continuous


def verify_row(row):
    a = [1 if c == "+" else -1 for c in row["A"]]
    b = [1 if c == "+" else -1 for c in row["B"]]
    return is_legendre_pair(a, b)[0]


def write_md(results, continuous, lengths, out):
    lines = []
    lines.append("# Legendre pairs found\n")
    lines.append(f"Generated by `collect_pairs.py` over $\\ell \\in "
                 f"[{lengths[0]}, {lengths[-1]}]$. Sequences are shown as +/- "
                 "strings (`+` = +1, `-` = -1); every pair below is verified by "
                 "`is_legendre_pair`.\n")

    titles = {
        "exhaustive": "Exhaustive search (PAF-vector bucketing, early stop)",
        "greedy": "Local search -- greedy (accept only if $E$ strictly decreases)",
        "sideways": "Local search -- sideways (accept if $E$ does not increase)",
        "anneal": "Local search -- simulated annealing (Metropolis)",
        "threshold": "Local search -- magnitude-threshold heuristic ($E>20\\ell$ reroll)",
        "basinhop": "Local search -- basin-hopping / iterated local search",
    }
    order = ["exhaustive", *LOCAL_STRATEGIES]
    for m in order:
        rows = results[m]
        lines.append(f"\n## {titles[m]}\n")
        if not rows:
            lines.append("_No pair found within the budget._\n")
            continue
        lines.append("| $\\ell$ | A | B | time (s) | parameters |")
        lines.append("|---:|---|---|---:|---|")
        for r in rows:
            lines.append(f"| {r['ell']} | `{r['A']}` | `{r['B']}` | "
                         f"{r['time']:.4f} | {r['params']} |")
        lines.append("")

    lines.append("\n## Continuous gradient descent\n")
    lines.append(f"Found **{continuous['solved']}/{continuous['total']}** pairs "
                 "(round-to-sign), and only at the smallest length(s) where the "
                 "space is tiny enough that a rounded critical point lands on a "
                 "pair by luck. Continuous descent generally settles at "
                 "non-binary critical points whose sign-rounding leaves $E>0$, so "
                 "it is not a viable search method; see `continuous_descent.py`. "
                 "Best rounded $E$ per length (0 = success): "
                 f"{continuous['best_round']}.\n")

    with open(out, "w") as f:
        f.write("\n".join(lines))
    print(f"saved -> {out}")


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--min", type=int, default=5)
    p.add_argument("--max", type=int, default=21)
    p.add_argument("--restarts", type=int, default=200)
    p.add_argument("--steps", type=int, default=12000)
    p.add_argument("--t0", type=float, default=3.0)
    p.add_argument("--t-end", type=float, default=0.05)
    p.add_argument("--seed", type=int, default=0, help="RNG seed (default 0)")
    p.add_argument("--out", default="found_pairs.md")
    args = p.parse_args()

    lengths = list(range(args.min | 1, args.max + 1, 2))
    results, continuous = collect(lengths, args.restarts, args.steps,
                                  args.t0, args.t_end, args.seed)

    # sanity: every tabulated pair must verify
    bad = [(m, r["ell"]) for m, rows in results.items() for r in rows
           if not verify_row(r)]
    if bad:
        print(f"WARNING: unverified rows: {bad}")
    else:
        total = sum(len(rows) for rows in results.values())
        print(f"all {total} tabulated pairs verified as genuine Legendre pairs")

    write_md(results, continuous, lengths, args.out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
