"""compare_databases.py — cross-check two Legendre-pair databases class-by-class.

Two databases store inequivalent Legendre pairs of odd length ``ell``:

  * MINE   : ``rle_experiment/results/lps/LP{ell}.csv``      header ``index,u,v``,
             sequences as ``+``/``-`` strings (``+`` = +1, ``-`` = -1);
  * FRIEND : ``Legendre_database/legendre_pair{ell}.csv``    header
             ``seq1,seq2,energy1,energy2``, sequences as ``1``/``0`` strings
             (``1`` = +1, ``0`` = -1).

Both quotient Legendre pairs by the SAME equivalence group GG (Bulutoglu-
Baczkowski-Yauney, "Determining the group that sends each Legendre pair to an
equivalent Legendre pair"), generated by

  * independent cyclic shift of each sequence      c_i(u), c_j(v)   (eq 1.4);
  * a COUPLED decimation d_k on both, with v allowed the mirror -k  (eqs 1.4/1.5,
    i.e. the two sequences share |k|: (d_k u, d_{+/-k} v));
  * the switch s(u,v) = (v,u);
  * sign normalization to row-sum +1 ("sum 1"): each Legendre sequence has sum
    exactly +/-1 (a^2+b^2 = 2), so we pin the +1 representative per sequence.

CANONICAL REPRESENTATIVE (this file): the LEXICOGRAPHICALLY GREATEST element of
the orbit under GG, with the convention +1 > -1 (i.e. the pair with the longest
run of leading +1's).  Because shifts of u and v are independent and decimation
is coupled, the orbit-max factorizes:

    canonical(u, v) = max over  k in units(ell),  eps in {+1,-1},  swap in {0,1}
                      of   ( maxrot(decimate(u, k)),  maxrot(decimate(v, eps*k)) )

where ``maxrot`` is the greatest cyclic rotation (Booth on the negated sequence:
maxrot(x) = -least_rotation_seq(-x)).  This is a COMPLETE invariant of the GG
class, so two pairs share a canonical iff they are equivalent.

OUTPUT (per common ell): ``db_comparison/compare_LP{ell}.csv`` with columns

    canonical_u, canonical_v, mine, mine_index, friend, friend_index

``mine`` / ``friend`` are ``X`` when that database contains the class, blank
otherwise; the index columns carry the row index within each database (multiple
indices ``;``-joined if a database lists the class more than once).  Rows present
in only ONE database (the genuine discrepancies) are floated to the TOP; the rest
follow.  Within each block, rows are sorted lexicographically by the canonical
representative.
"""
from __future__ import annotations

import csv
import os
import sys
from collections import OrderedDict
from typing import Dict, List, Tuple

import numpy as np

_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(_HERE, "rle_experiment"))

from lp_rle.symmetry import units, decimate, least_rotation_seq  # noqa: E402

MINE_DIR = os.path.join(_HERE, "rle_experiment", "results", "lps")
FRIEND_DIR = os.path.join(_HERE, "Legendre_database")
OUT_DIR = os.path.join(_HERE, "db_comparison")


# --------------------------------------------------------------------------- #
# parsing: both databases -> lists of (row_index, u, v) as +/-1 int8 arrays
# --------------------------------------------------------------------------- #
def _pm_from_plusminus(s: str) -> np.ndarray:
    """'+'/'-' string -> +/-1 int8 array ('+' = +1, '-' = -1)."""
    b = np.frombuffer(s.encode(), np.uint8)
    return np.where(b == ord('+'), 1, -1).astype(np.int8)


def _pm_from_bits(s: str) -> np.ndarray:
    """'1'/'0' string -> +/-1 int8 array ('1' = +1, '0' = -1)."""
    b = np.frombuffer(s.encode(), np.uint8)
    return np.where(b == ord('1'), 1, -1).astype(np.int8)


def parse_mine(path: str) -> List[Tuple[str, np.ndarray, np.ndarray]]:
    out = []
    with open(path, newline="") as f:
        for row in csv.DictReader(f):
            out.append((row["index"], _pm_from_plusminus(row["u"]),
                        _pm_from_plusminus(row["v"])))
    return out


def parse_friend(path: str) -> List[Tuple[str, np.ndarray, np.ndarray]]:
    out = []
    with open(path, newline="") as f:
        for i, row in enumerate(csv.DictReader(f)):
            out.append((str(i), _pm_from_bits(row["seq1"]),
                        _pm_from_bits(row["seq2"])))
    return out


# --------------------------------------------------------------------------- #
# canonical representative under GG (lexicographic MAX, +1 > -1)
# --------------------------------------------------------------------------- #
def _normalize(v: np.ndarray) -> np.ndarray:
    """Pin the row-sum +1 representative (the 'sum 1' symmetry)."""
    v = np.asarray(v, dtype=np.int8)
    return v if int(v.sum()) > 0 else (-v).astype(np.int8)


def maxrot(v: np.ndarray) -> np.ndarray:
    """Greatest cyclic rotation under +1 > -1 (= -least_rotation(-v))."""
    return (-least_rotation_seq((-np.asarray(v, dtype=np.int8)))).astype(np.int8)


def _enc(v: np.ndarray) -> bytes:
    """Order-preserving key with +1 > -1 (+1 -> 0x01, -1 -> 0x00)."""
    return (np.asarray(v) > 0).astype(np.uint8).tobytes()


def _to_str(v: np.ndarray) -> str:
    return "".join("+" if x > 0 else "-" for x in v)


def canonical(u: np.ndarray, v: np.ndarray) -> Tuple[str, str]:
    """Lexicographically greatest (u, v) over the full GG orbit; +1 > -1.

    Returns the representative as a ('+/-' , '+/-') string pair, which is a
    complete invariant of the equivalence class.
    """
    u = _normalize(u)
    v = _normalize(v)
    L = u.shape[0]
    us = units(L)
    Ru = {k: maxrot(decimate(u, k)) for k in us}
    Rv = {k: maxrot(decimate(v, k)) for k in us}

    best_key = None
    best_pair = None
    for k in us:
        nk = (L - k) % L  # -k mod L, also a unit
        # coupling b = +/- k  (eqs 1.4 / 1.5), with and without the switch
        for a_arr, b_arr in ((Ru[k], Rv[k]), (Ru[k], Rv[nk]),
                             (Rv[k], Ru[k]), (Rv[nk], Ru[k])):
            key = (_enc(a_arr), _enc(b_arr))
            if best_key is None or key > best_key:
                best_key = key
                best_pair = (a_arr, b_arr)
    return _to_str(best_pair[0]), _to_str(best_pair[1])


# --------------------------------------------------------------------------- #
# per-ell comparison
# --------------------------------------------------------------------------- #
def _canon_index(entries) -> "OrderedDict[Tuple[str, str], List[str]]":
    """Map canonical rep -> list of row indices in this database."""
    idx: "OrderedDict[Tuple[str, str], List[str]]" = OrderedDict()
    for ridx, u, v in entries:
        key = canonical(u, v)
        idx.setdefault(key, []).append(ridx)
    return idx


CMP_FIELDS = ["canonical_u", "canonical_v", "mine", "mine_index",
              "friend", "friend_index"]


def compare_ell(ell: int) -> List[Dict]:
    """Build the comparison rows for one ell (discrepancies floated to top)."""
    mine = _canon_index(parse_mine(os.path.join(MINE_DIR, f"LP{ell}.csv")))
    friend = _canon_index(parse_friend(
        os.path.join(FRIEND_DIR, f"legendre_pair{ell}.csv")))

    keys = set(mine) | set(friend)
    rows = []
    for key in keys:
        in_mine, in_friend = key in mine, key in friend
        rows.append({
            "canonical_u": key[0],
            "canonical_v": key[1],
            "mine": "X" if in_mine else "",
            "mine_index": ";".join(mine.get(key, [])),
            "friend": "X" if in_friend else "",
            "friend_index": ";".join(friend.get(key, [])),
            "_both": in_mine and in_friend,
        })
    # unmatched (in exactly one DB) first; then lexicographic by representative
    rows.sort(key=lambda r: (r["_both"], r["canonical_u"], r["canonical_v"]))
    for r in rows:
        del r["_both"]
    return rows


def write_ell(ell: int, out_dir: str = OUT_DIR) -> Tuple[str, int, int]:
    """Write compare_LP{ell}.csv; return (path, n_rows, n_discrepancies)."""
    rows = compare_ell(ell)
    os.makedirs(out_dir, exist_ok=True)
    path = os.path.join(out_dir, f"compare_LP{ell}.csv")
    with open(path, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=CMP_FIELDS)
        w.writeheader()
        w.writerows(rows)
    disc = sum(1 for r in rows if not (r["mine"] and r["friend"]))
    return path, len(rows), disc


def common_lengths() -> List[int]:
    """Odd ell for which BOTH databases have a file."""
    out = []
    for ell in range(3, 60, 2):
        if os.path.exists(os.path.join(MINE_DIR, f"LP{ell}.csv")) and \
           os.path.exists(os.path.join(FRIEND_DIR, f"legendre_pair{ell}.csv")):
            out.append(ell)
    return out


if __name__ == "__main__":
    print(f"{'ell':>3} {'classes':>7} {'mine_only':>9} {'friend_only':>11} "
          f"{'both':>5}")
    print("-" * 40)
    total_disc = 0
    for ell in common_lengths():
        rows = compare_ell(ell)
        write_ell(ell)
        mine_only = sum(1 for r in rows if r["mine"] and not r["friend"])
        friend_only = sum(1 for r in rows if r["friend"] and not r["mine"])
        both = sum(1 for r in rows if r["mine"] and r["friend"])
        total_disc += mine_only + friend_only
        flag = "  <-- DIFFERS" if (mine_only or friend_only) else ""
        print(f"{ell:>3} {len(rows):>7} {mine_only:>9} {friend_only:>11} "
              f"{both:>5}{flag}", flush=True)
    print(f"\nwrote {len(common_lengths())} files to {OUT_DIR}")
    print(f"total discrepancy classes (in exactly one DB): {total_disc}")
