"""Legendre-pair census via signature counting + GG-orbit structure.

For each odd length ``ell`` we

  * count all Legendre pairs exactly (a signature census over the C(ell,(ell-1)/2)
    normalized sequences -- cheap, since that binomial is <= 92378 for ell<=19), and
  * partition the pair set into orbits of the "good group" GG (coordinate
    permutations that preserve the LP property), reporting orbit sizes and
    stabilizers.

The facts the code relies on (NOT re-derived at runtime -- see README.md):

Legendre pair (normalized).  u, v in {-1,+1}^ell of odd length ell, each with
exactly (ell-1)/2 entries equal to -1 (so 1.u = 1.v = +1), satisfying
    PAF(u,j) + PAF(v,j) = -2   for all j != 0   (mod ell),
where PAF(w,j) = sum_i w_i w_{(i-j) mod ell}.

Signature form (necessary AND sufficient).  With
    sigma(u) = (PAF(u,1), ..., PAF(u,(ell-1)/2))   (integer valued),
(u,v) is an LP  <=>  sigma(v) = (-2,...,-2) - sigma(u).  So counting LPs is a
convolution of the signature histogram with its complement.

The good group GG.  |GG| = 4 * ell^2 * phi(ell).  GG acts by coordinate
permutations (hence preserves normalization), generated by
    shift_u  : (c1(u), v)             c1(w)_i = w_{i-1 mod ell}
    shift_v  : (u, c1(v))
    decim    : (d_g(u), d_g(v))        d_k(w)_i = w_{i k^{-1} mod ell}
    reverse_v: (u, d_{-1}(v))
    switch   : (v, u)
Each generator is a permutation of the ell positions; on the bitmask of "-1"
positions, shift sends p -> p+1, decimation-by-k sends p -> p*k, reversal sends
p -> -p (all mod ell).

We ENUMERATE as ground truth and use GG only to organize/validate: a single
seed's orbit equals the whole LP set ONLY when there is one class (N=1). The
code never claims otherwise -- it prints the caveat when N>1.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import os
import pickle
import sys
from collections import defaultdict
from itertools import combinations, islice
from math import gcd

import numpy as np

# Reuse the FFT PAF from the sibling toolkit for cross-checks/tests.
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "src"))
from legendre_pairs import paf as _fft_paf  # noqa: E402

try:                                    # optional progress bar
    from tqdm import tqdm
except Exception:                       # pragma: no cover - tqdm is optional
    def tqdm(it=None, **kw):
        return it if it is not None else iter(())

HERE = os.path.dirname(os.path.abspath(__file__))
CKPT_DIR = os.path.join(HERE, "ckpt")
SEED_DIR = os.path.join(HERE, "seeds")
CENSUS_CSV = os.path.join(HERE, "census.csv")
COST_CSV = os.path.join(HERE, "cost.csv")
CHUNK = 50_000                          # checkpoint / batch granularity K


# --------------------------------------------------------------------------- #
# number theory
# --------------------------------------------------------------------------- #
def euler_phi(n: int) -> int:
    result, m, p = n, n, 2
    while p * p <= m:
        if m % p == 0:
            while m % p == 0:
                m //= p
            result -= result // p
        p += 1
    if m > 1:
        result -= result // m
    return result


def group_order(ell: int) -> int:
    """|GG| = 4 * ell^2 * phi(ell)."""
    return 4 * ell * ell * euler_phi(ell)


def units(ell: int) -> list[int]:
    """The multiplicative group Z_ell^x."""
    return [k for k in range(1, ell) if gcd(k, ell) == 1]


# --------------------------------------------------------------------------- #
# signatures
# --------------------------------------------------------------------------- #
def mask_to_seq(mask: int, ell: int) -> np.ndarray:
    """+-1 sequence whose ``-1`` positions are the set bits of ``mask``."""
    u = np.ones(ell, dtype=np.int64)
    for p in range(ell):
        if (mask >> p) & 1:
            u[p] = -1
    return u


def signature(mask: int, ell: int) -> tuple[int, ...]:
    """sigma(u) = (PAF(u,1),...,PAF(u,(ell-1)/2)) as an exact integer tuple.

    Computed by FFT (O(ell log ell)); values must be integers, which we assert
    (we key dictionaries on these ints -- never on floats)."""
    u = mask_to_seq(mask, ell).astype(float)
    r = np.fft.ifft(np.abs(np.fft.fft(u)) ** 2).real
    h = (ell - 1) // 2
    s = r[1:h + 1]
    si = np.rint(s).astype(np.int64)
    if np.max(np.abs(s - si)) > 1e-6:
        raise AssertionError(f"non-integer PAF at mask={mask}, ell={ell}: {s}")
    return tuple(int(x) for x in si)


def _sig_worker(args):
    mask, ell = args
    return mask, signature(mask, ell)


def complement(sig: tuple[int, ...]) -> tuple[int, ...]:
    """(-2,...,-2) - sigma."""
    return tuple(-2 - x for x in sig)


# --------------------------------------------------------------------------- #
# STEP 1 -- group order table
# --------------------------------------------------------------------------- #
def step1(lmin: int, lmax: int) -> None:
    print(f"{'ell':>4} | {'phi(ell)':>8} | {'|GG| = 4*ell^2*phi(ell)':>24}")
    print("-" * 44)
    for ell in range(lmin | 1, lmax + 1, 2):     # odd only
        print(f"{ell:>4} | {euler_phi(ell):>8} | {group_order(ell):>24,}")


# --------------------------------------------------------------------------- #
# STEP 2A/B -- signature census + materialized LP set (with checkpointing)
# --------------------------------------------------------------------------- #
def _ckpt_path(ell: int) -> str:
    return os.path.join(CKPT_DIR, f"ell{ell}.pkl")


def _save_ckpt(ell, count, sigmap, last_index):
    os.makedirs(CKPT_DIR, exist_ok=True)
    path = _ckpt_path(ell)
    tmp = path + ".tmp"
    with open(tmp, "wb") as f:
        pickle.dump({"ell": ell, "last_index": last_index,
                     "count": dict(count),
                     "sigmap": {k: list(v) for k, v in sigmap.items()}}, f)
    os.replace(tmp, path)               # atomic -- never a half-written ckpt


def _load_ckpt(ell):
    path = _ckpt_path(ell)
    if not os.path.exists(path):
        return None
    with open(path, "rb") as f:
        d = pickle.load(f)
    if d.get("ell") != ell:
        raise ValueError(f"checkpoint ell={d.get('ell')} != {ell}")
    count = defaultdict(int, d["count"])
    sigmap = defaultdict(list, {k: list(v) for k, v in d["sigmap"].items()})
    return count, sigmap, int(d["last_index"])


def census_signatures(ell: int, cores: int = 1, resume: bool = True,
                      progress: bool = True):
    """Enumerate normalized u, tally sigma(u); returns (count, sigmap).

    ``count[sig]`` = #sequences with that signature; ``sigmap[sig]`` = their
    bitmasks. Checkpointed every ``CHUNK`` combinations to ``ckpt/ell{ell}.pkl``
    and resumable, so a run can be stopped and restarted at any time."""
    neg = (ell - 1) // 2
    total = math.comb(ell, neg)

    count = defaultdict(int)
    sigmap = defaultdict(list)
    start = 0
    if resume:
        loaded = _load_ckpt(ell)
        if loaded is not None:
            count, sigmap, start = loaded
            if progress:
                print(f"[ell={ell}] resuming from checkpoint at index {start}")

    combos = islice(combinations(range(ell), neg), start, None)
    idx = start
    pool = None
    if cores > 1:
        import multiprocessing as mp
        pool = mp.Pool(cores)

    bar = tqdm(total=total, initial=start, desc=f"ell={ell} sigs",
               disable=not progress)
    try:
        while True:
            chunk = list(islice(combos, CHUNK))
            if not chunk:
                break
            masks = [sum(1 << p for p in combo) for combo in chunk]
            if pool is not None:
                results = pool.map(_sig_worker, [(m, ell) for m in masks])
            else:
                results = [(m, signature(m, ell)) for m in masks]
            for mask, sig in results:
                count[sig] += 1
                sigmap[sig].append(mask)
            idx += len(chunk)
            _save_ckpt(ell, count, sigmap, idx)
            if bar is not None:
                bar.update(len(chunk))
    finally:
        if pool is not None:
            pool.close()
            pool.join()
        if hasattr(bar, "close"):
            bar.close()
    return count, sigmap


def totals_from_count(count) -> tuple[int, int, int]:
    """(T_ordered, T_unordered, T_diag) from the signature histogram."""
    t_ordered = 0
    t_diag = 0
    for sig, c in count.items():
        comp = complement(sig)
        t_ordered += c * count.get(comp, 0)
        if comp == sig:
            t_diag += c
    t_unordered = (t_ordered + t_diag) // 2
    return t_ordered, t_unordered, t_diag


# --------------------------------------------------------------------------- #
# STEP 2C/D -- GG orbits over the ordered LP pair set
# --------------------------------------------------------------------------- #
def _perm_apply(mask: int, perm: list[int]) -> int:
    """Relabel the set bits of ``mask`` by ``perm`` (a position permutation)."""
    out = 0
    p = 0
    m = mask
    while m:
        if m & 1:
            out |= 1 << perm[p]
        m >>= 1
        p += 1
    return out


def _generators(ell: int):
    """Position permutations for the GG generators.

    Returns ``(shift, neg, muls)`` where ``shift`` is p->p+1, ``neg`` is p->-p,
    and ``muls`` is the list of decimation permutations p->p*k for every unit k
    (covers Z_ell^x even when it is non-cyclic, e.g. ell=15)."""
    shift = [(p + 1) % ell for p in range(ell)]
    neg = [(-p) % ell for p in range(ell)]
    muls = [[(p * k) % ell for p in range(ell)] for k in units(ell)]
    return shift, neg, muls


def _neighbors(pair, ell, gens):
    """All GG-generator images of an ordered pair ``(bu, bv)``."""
    bu, bv = pair
    shift, neg, muls = gens
    out = [
        (_perm_apply(bu, shift), bv),        # shift_u
        (bu, _perm_apply(bv, shift)),        # shift_v
        (bv, bu),                            # switch
        (bu, _perm_apply(bv, neg)),          # reverse_v
    ]
    for mul in muls:                         # decim (both members)
        out.append((_perm_apply(bu, mul), _perm_apply(bv, mul)))
    return out


class _UF:
    def __init__(self):
        self.parent = {}

    def find(self, x):
        self.parent.setdefault(x, x)
        root = x
        while self.parent[root] != root:
            root = self.parent[root]
        while self.parent[x] != root:      # path compression
            self.parent[x], x = root, self.parent[x]
        return root

    def union(self, a, b):
        ra, rb = self.find(a), self.find(b)
        if ra != rb:
            self.parent[ra] = rb


def ordered_lp_pairs(count, sigmap):
    """Yield every ordered LP pair (bu, bv) as bitmask tuples."""
    for sig, masks_u in sigmap.items():
        comp = complement(sig)
        masks_v = sigmap.get(comp)
        if not masks_v:
            continue
        for bu in masks_u:
            for bv in masks_v:
                yield (bu, bv)


def gg_orbits(ell, count, sigmap):
    """Union-find partition of the ordered LP set under GG.

    Returns ``(orbits, pairs)`` where ``orbits`` is a list of orbit sizes and
    ``pairs`` maps each orbit root -> a representative pair."""
    gens = _generators(ell)
    nodes = list(ordered_lp_pairs(count, sigmap))
    nodeset = set(nodes)
    uf = _UF()
    for pair in nodes:
        uf.find(pair)                          # register
    for pair in nodes:
        for nb in _neighbors(pair, ell, gens):
            # GG preserves the LP property, so every image must be a known node.
            if nb not in nodeset:
                raise AssertionError(
                    f"GG image {nb} of {pair} is not an LP -- generator bug")
            uf.union(pair, nb)
    groups = defaultdict(list)
    for pair in nodes:
        groups[uf.find(pair)].append(pair)
    reps = {root: members[0] for root, members in groups.items()}
    sizes = [len(m) for m in groups.values()]
    return sizes, reps, nodeset, dict(groups)


def seed_expand(seed, ell):
    """BFS from one seed over the GG generators -- NO candidate enumeration.

    Returns the full orbit (set of ordered pairs) reachable from ``seed``."""
    gens = _generators(ell)
    seen = {seed}
    frontier = [seed]
    while frontier:
        nxt = []
        for pair in frontier:
            for nb in _neighbors(pair, ell, gens):
                if nb not in seen:
                    seen.add(nb)
                    nxt.append(nb)
        frontier = nxt
    return seen


# --------------------------------------------------------------------------- #
# CSV helpers
# --------------------------------------------------------------------------- #
CENSUS_HEADER = ["ell", "M", "M2", "GG", "T_ordered", "T_unordered", "T_diag",
                 "N_classes", "min_orbit", "max_orbit", "max_orbit_over_GG"]


def append_census_row(row: dict) -> None:
    exists = os.path.exists(CENSUS_CSV)
    with open(CENSUS_CSV, "a", newline="") as f:
        w = csv.DictWriter(f, fieldnames=CENSUS_HEADER)
        if not exists:
            w.writeheader()
        w.writerow(row)


def write_cost_header() -> None:
    """cost.csv is produced by --greedy (Step 3, not yet implemented); we write
    just the documented header so the deliverable exists."""
    if os.path.exists(COST_CSV):
        return
    with open(COST_CSV, "w", newline="") as f:
        csv.writer(f).writerow(
            ["ell", "restarts", "successes", "q_empirical", "N_delta_est"])


# --------------------------------------------------------------------------- #
# STEP 2 driver
# --------------------------------------------------------------------------- #
def step2(lmin, lmax, cores=1, do_orbits=False, progress=True):
    for ell in range(lmin, lmax + 1):
        if ell % 2 == 0:                       # even ell: no LPs, T = 0
            if progress:
                print(f"[ell={ell}] even -> skip (T=0)")
            continue

        neg = (ell - 1) // 2
        M = math.comb(ell, neg)
        GG = group_order(ell)
        count, sigmap = census_signatures(ell, cores=cores, progress=progress)
        T_ordered, T_unordered, T_diag = totals_from_count(count)

        row = {"ell": ell, "M": M, "M2": M * M, "GG": GG,
               "T_ordered": T_ordered, "T_unordered": T_unordered,
               "T_diag": T_diag, "N_classes": "", "min_orbit": "",
               "max_orbit": "", "max_orbit_over_GG": ""}

        print(f"[ell={ell}] M={M}  T_ordered={T_ordered}  "
              f"T_unordered={T_unordered}  T_diag={T_diag}")

        if do_orbits:
            sizes, reps, nodeset, groups = gg_orbits(ell, count, sigmap)
            # asserts: partition consistency + orbit-stabilizer sanity
            assert sum(sizes) == T_ordered, (
                f"sum(orbit sizes)={sum(sizes)} != T_ordered={T_ordered}")
            for s in sizes:
                assert GG % s == 0, f"orbit size {s} does not divide |GG|={GG}"
                assert s <= GG, f"orbit size {s} exceeds |GG|={GG}"
            N = len(sizes)
            row.update({"N_classes": N, "min_orbit": min(sizes),
                        "max_orbit": max(sizes),
                        "max_orbit_over_GG": f"{max(sizes) / GG:.6g}"})

            # shortcut validation: BFS orbit == union-find orbit for each class
            os.makedirs(SEED_DIR, exist_ok=True)
            seeds = []
            for root, rep in reps.items():
                bfs = seed_expand(rep, ell)
                uf_size = sizes[list(reps).index(root)]
                assert len(bfs) == uf_size, (
                    f"seed_expand size {len(bfs)} != orbit size {uf_size}")
                seeds.append([int(rep[0]), int(rep[1])])
            with open(os.path.join(SEED_DIR, f"ell{ell}.json"), "w") as f:
                json.dump({"ell": ell, "n_classes": N, "seeds": seeds}, f, indent=2)

            if N == 1:
                # single seed's orbit IS the whole LP set -- and we verified it.
                assert seed_expand(reps[next(iter(reps))], ell).__len__() == T_ordered
                print(f"[ell={ell}] N_classes=1  -> single seed expands to the "
                      f"entire LP set ({T_ordered} ordered pairs).")
            else:
                print(f"[ell={ell}] N_classes={N} > 1  -> CAVEAT: a single seed "
                      f"is INCOMPLETE; it misses {N - 1} of {N} classes. "
                      f"Orbit sizes: {sorted(sizes)}")

        append_census_row(row)
    write_cost_header()


# --------------------------------------------------------------------------- #
# STEP 3 -- greedy random search cost (STUB)
# --------------------------------------------------------------------------- #
def step3_greedy(*args, **kwargs):
    raise NotImplementedError(
        "Step 3 (--greedy) is a documented placeholder, not working code.\n"
        "Intended design: hill-climb on fitness F(u,v) = sum_j (PAF_u(j) + "
        "PAF_v(j) + 2)^2 (zero iff LP) by single-coordinate sign flips, with "
        "many random restarts. Record the per-restart empirical success rate q "
        "(fraction of restarts reaching F=0), then estimate the expected number "
        "of restarts to first success as N_delta ~ log(delta) / log(1 - q) for "
        "a target failure probability delta. Emit ell, restarts, successes, "
        "q_empirical, N_delta_est to cost.csv.")


# --------------------------------------------------------------------------- #
# CLI
# --------------------------------------------------------------------------- #
def main() -> int:
    p = argparse.ArgumentParser(description="Legendre-pair census + GG orbits.")
    p.add_argument("--step", type=int, choices=[1, 2, 3], default=2,
                   help="1: group-order table; 2: census+orbits; 3: greedy (stub)")
    p.add_argument("--lmin", type=int, default=5)
    p.add_argument("--lmax", type=int, default=20)
    p.add_argument("--cores", type=int, default=1,
                   help="worker processes for the signature census")
    p.add_argument("--orbits", action="store_true",
                   help="also compute the GG-orbit partition (Step 2C/D)")
    p.add_argument("--greedy", action="store_true",
                   help="(Step 3) register the flag; raises NotImplementedError")
    p.add_argument("--quiet", action="store_true")
    args = p.parse_args()

    if args.greedy or args.step == 3:
        step3_greedy()
        return 0
    if args.step == 1:
        step1(args.lmin, args.lmax)
        return 0
    step2(args.lmin, args.lmax, cores=args.cores, do_orbits=args.orbits,
          progress=not args.quiet)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
